/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import classes.CSVFileManager;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.UUID;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EMAN
 */
public class FrmNewAccount extends javax.swing.JFrame {
    
    private static final java.lang.String JDBC_URL = "jdbc:mysql://sql12.freesqldatabase.com:3306/sql12713427";
    private static final java.lang.String USERNAME = "sql12713427";
    private static final java.lang.String PASSWORD = "7l87SNw2yD";
    
    //image database
    private static final java.lang.String imgJDBC_URL = "jdbc:mysql://sql12.freesqldatabase.com:3306/sql12713671";
    private static final java.lang.String imgUSERNAME = "sql12713671";
    private static final java.lang.String imgPASSWORD = "KwHeJTT2C4";

    private FrmITpage itPageRef;
    private JTable tblAccounts;
    /**
     * Creates new form FrmNewAccount
     */
    public FrmNewAccount(FrmITpage itPageRef) {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null); // Center the frame
        setPreferredSize(new Dimension(586, 467));
        
        // Set frame properties
        pack();  // Adjust size to the preferred size
    
        displayBgFromDatabase("FrmNewAccount");
        
        this.itPageRef = itPageRef;
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    // Method to fetch and display image from the database
    private void displayBgFromDatabase(String frameName) {
        try (Connection conn = DriverManager.getConnection(imgJDBC_URL, imgUSERNAME, imgPASSWORD)) {
            // Prepare SQL statement to retrieve image data from the database
            String SELECT_IMAGE = "SELECT Img FROM Image WHERE Frame = ?";

            try (PreparedStatement pstmt = conn.prepareStatement(SELECT_IMAGE)) {
                // Set the frame name as a parameter for the prepared statement
                pstmt.setString(1, frameName);

                // Execute the SELECT statement
                ResultSet resultSet = pstmt.executeQuery();

                // Check if a result was found
                if (resultSet.next()) {
                    // Retrieve the image data as a byte array
                    byte[] imgByteArray = resultSet.getBytes("Img");

                    // Convert the byte array to an ImageIcon
                    ImageIcon icon = new ImageIcon(imgByteArray);

                    // Set the ImageIcon as the icon for the JLabel
                    jLabel1.setIcon(icon);
                } else {
                    System.out.println("Image not found.");
                }
            } catch (SQLException e) {
                e.printStackTrace();
                // Handle the exception appropriately
            }
        } catch (SQLException e) {
            e.printStackTrace();
            // Handle the exception appropriately
        }
    }   

    //event handler method for close button
    private void FrameClose(java.awt.event.MouseEvent evt) {                            
        this.dispose();
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsername = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        lblRoleAccess = new javax.swing.JLabel();
        jCBRoleAccess = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblEmployeeNum = new javax.swing.JLabel();
        txtEmployeeNum = new javax.swing.JTextField();
        btnViewEmp = new javax.swing.JButton();
        lblNote = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(586, 467));
        setMinimumSize(new java.awt.Dimension(586, 467));
        setPreferredSize(new java.awt.Dimension(586, 467));
        setSize(new java.awt.Dimension(586, 467));
        getContentPane().setLayout(null);

        lblUsername.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Username:");
        getContentPane().add(lblUsername);
        lblUsername.setBounds(120, 190, 84, 18);

        txtUsername.setBackground(new java.awt.Color(255, 255, 255));
        txtUsername.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtUsername.setForeground(new java.awt.Color(68, 53, 53));
        getContentPane().add(txtUsername);
        txtUsername.setBounds(240, 190, 230, 28);

        lblPassword.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password:");
        getContentPane().add(lblPassword);
        lblPassword.setBounds(120, 250, 82, 18);

        txtPassword.setBackground(new java.awt.Color(255, 255, 255));
        txtPassword.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(68, 53, 53));
        getContentPane().add(txtPassword);
        txtPassword.setBounds(240, 250, 230, 28);

        lblRoleAccess.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblRoleAccess.setForeground(new java.awt.Color(255, 255, 255));
        lblRoleAccess.setText("Role Access:");
        getContentPane().add(lblRoleAccess);
        lblRoleAccess.setBounds(120, 310, 98, 18);

        jCBRoleAccess.setBackground(new java.awt.Color(255, 255, 255));
        jCBRoleAccess.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jCBRoleAccess.setForeground(new java.awt.Color(68, 53, 53));
        jCBRoleAccess.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Employee", "HR", "Payroll", "IT" }));
        getContentPane().add(jCBRoleAccess);
        jCBRoleAccess.setBounds(240, 310, 230, 28);

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(79, 59, 59));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave);
        btnSave.setBounds(320, 360, 76, 28);

        btnCancel.setBackground(new java.awt.Color(255, 255, 255));
        btnCancel.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(79, 59, 59));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel);
        btnCancel.setBounds(400, 360, 80, 28);

        lblEmployeeNum.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        lblEmployeeNum.setForeground(new java.awt.Color(255, 255, 255));
        lblEmployeeNum.setText("Employee ID:");
        getContentPane().add(lblEmployeeNum);
        lblEmployeeNum.setBounds(120, 110, 120, 17);

        txtEmployeeNum.setBackground(new java.awt.Color(255, 255, 255));
        txtEmployeeNum.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtEmployeeNum.setForeground(new java.awt.Color(68, 53, 53));
        getContentPane().add(txtEmployeeNum);
        txtEmployeeNum.setBounds(240, 110, 230, 28);

        btnViewEmp.setBackground(new java.awt.Color(255, 255, 255));
        btnViewEmp.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btnViewEmp.setForeground(new java.awt.Color(59, 54, 54));
        btnViewEmp.setText("View Employees");
        btnViewEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewEmpActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewEmp);
        btnViewEmp.setBounds(285, 140, 140, 30);

        lblNote.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        lblNote.setForeground(new java.awt.Color(64, 52, 52));
        lblNote.setText("Note: Refresh the table after adding a new account.");
        getContentPane().add(lblNote);
        lblNote.setBounds(47, 410, 440, 17);

        jLabel1.setText("newacc");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -30, 590, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        // Check if any of the text fields are empty
        if (txtUsername.getText().isEmpty() || txtPassword.getText().isEmpty() || jCBRoleAccess.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Exit the method without saving
        }
        
        // Prepare accountInfo array with account information
        String[] accountInfo = {
            txtUsername.getText(),                              // Username
            txtPassword.getText(),                              // Password
            jCBRoleAccess.getSelectedItem().toString(),         //Role Access
        };

        // Update table in FrmITpage with the new account record
        itPageRef.updateTable(accountInfo);

        // Update CSV file with data from the table in FrmITpage
        String csvFilePath = "src/main/java/files/Users.csv";
        JTable table = itPageRef.getTblAccounts(); // Assuming getTable() returns the JTable instance in FrmITpage
        CSVFileManager.updateCSVFile(csvFilePath, table);

        // Show success message
        JOptionPane.showMessageDialog(this, "Account saved successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);

        // Clear text fields after saving
        clearTextFields();

    }//GEN-LAST:event_btnSaveActionPerformed
*/
                                       
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // Check if any of the text fields are empty
        if (txtEmployeeNum.getText().isEmpty() || txtUsername.getText().isEmpty() || txtPassword.getText().isEmpty() || jCBRoleAccess.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Exit the method without saving
        }
        
        // Get the employee number text from the text field
        String employeeNumText = txtEmployeeNum.getText();

        // Check if the employee number contains only digits
        if (!employeeNumText.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Employee ID must be a valid integer.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Exit the method without saving
        }

        // Get the employee number from the text field
        int employeeNum = Integer.parseInt(txtEmployeeNum.getText());
        
        // Check if the employee exists
        try (Connection conn = DriverManager.getConnection(JDBC_URL, USERNAME, PASSWORD)) {
            if (!employeeEmployeeExists(conn, employeeNum)) {
                JOptionPane.showMessageDialog(this, "Employee ID does not exist.", "Error", JOptionPane.ERROR_MESSAGE);
                return; // Exit the method without saving
            }

        // Prepare accountInfo array with account information
        String[] accountInfo = {
            txtUsername.getText(),                              // Username
            txtPassword.getText(),                              // Password
            jCBRoleAccess.getSelectedItem().toString()         // Role Access
        };

            // Check if the employee number already exists
            if (employeeLoginExists(conn, employeeNum)) {
                JOptionPane.showMessageDialog(this, "An account for this Employee ID already exists.", "Error", JOptionPane.ERROR_MESSAGE);
                return; // Exit the method without saving
            }

            // Check if the username already exists
            if (usernameExists(conn, accountInfo[0])) {
                JOptionPane.showMessageDialog(this, "Username already exists. Please choose a different username.", "Error", JOptionPane.ERROR_MESSAGE);
                return; // Exit the method without saving
            }

            // Prepare the SQL INSERT statement for the account
            String loginSql = "INSERT INTO login (EmployeeNum, Username, Password, Role) VALUES (?, ?, ?, ?)";
            try (PreparedStatement statement = conn.prepareStatement(loginSql)) {
                // Set parameters for the prepared statement
                statement.setInt(1, employeeNum); // EmpID
                statement.setString(2, accountInfo[0]); // Username
                statement.setString(3, accountInfo[1]); // Password
                statement.setString(4, accountInfo[2]); // Role Access

                // Execute the insert statement for the account
                int rowsAffected = statement.executeUpdate();
                if (rowsAffected > 0) {
                    // Show success message
                    JOptionPane.showMessageDialog(this, "Account saved successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);

                    // Clear text fields after saving
                    clearTextFields();
                    
                    // Refresh tblAccounts in FrmITpage
                    if (itPageRef != null) {
                        itPageRef.refreshTblAccounts(); // Call refresh method
                    }

                    // Close the current frame
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to save account.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    // Method to refresh the tblResetPass table
    public void refreshTblAccounts() {
        // Refresh tblAccounts
        DefaultTableModel modelAccounts = (DefaultTableModel) tblAccounts.getModel();
        modelAccounts.setRowCount(0); // Clear existing rows

        // Retrieve updated data for tblAccounts from the database
        try (Connection conn = DriverManager.getConnection(JDBC_URL, USERNAME, PASSWORD)) {
            String sqlAccounts = "SELECT * FROM login ORDER BY EmployeeNum"; // Order by EmployeeNum column
            try (PreparedStatement statement = conn.prepareStatement(sqlAccounts);
                 ResultSet resultSet = statement.executeQuery()) {
                while (resultSet.next()) {
                    Object[] rowData = {
                        resultSet.getInt("EmployeeNum"),
                        resultSet.getString("Username"),
                        resultSet.getString("Password"),
                        resultSet.getString("Role")
                    };
                    modelAccounts.addRow(rowData); // Add row to the table model
                }
            }

            // Print a message to indicate that tblAccounts has been refreshed
            System.out.println("tblAccounts Refreshed.");

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    // Method to check if a username already exists in the database
    private boolean usernameExists(Connection conn, String username) throws SQLException {
        String query = "SELECT COUNT(*) AS count FROM login WHERE Username = ?";
        try (PreparedStatement statement = conn.prepareStatement(query)) {
            statement.setString(1, username);
            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    int count = resultSet.getInt("count");
                    return count > 0;
                }
            }
        }
        return false;
    }
    
    // Method to check if employee number already exists
    private boolean employeeLoginExists(Connection conn, int employeeNum) throws SQLException {
        String query = "SELECT COUNT(*) AS count FROM login WHERE EmployeeNum = ?";
        try (PreparedStatement statement = conn.prepareStatement(query)) {
            statement.setInt(1, employeeNum);
            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    int count = resultSet.getInt("count");
                    return count > 0; // Return true if count is greater than 0 (employee exists), false otherwise
                }
            }
        }
        return false;
    }

    // Method to check if employee number already exists
    private boolean employeeEmployeeExists(Connection conn, int employeeNum) throws SQLException {
        String query = "SELECT COUNT(*) AS count FROM employee WHERE EmployeeNum = ?";
        try (PreparedStatement statement = conn.prepareStatement(query)) {
            statement.setInt(1, employeeNum);
            try (ResultSet resultSet = statement.executeQuery()) {
                if (resultSet.next()) {
                    int count = resultSet.getInt("count");
                    return count > 0; // Return true if count is greater than 0 (employee exists), false otherwise
                }
            }
        }
        return false;
    }

    // Method for clearing text fields
    private void clearTextFields() {
        txtEmployeeNum.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
        jCBRoleAccess.setSelectedItem(null);
    }

    private FrmExistingEmployee existingEmployeeFrame;

    public void setExistingEmployeeFrame(FrmExistingEmployee existingEmployeeFrame) {
        this.existingEmployeeFrame = existingEmployeeFrame;
    }
    
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private boolean isExistingEmployeeFrameOpen = false; // Flag to track if the existing employee frame is open
    
    private void btnViewEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEmpActionPerformed
        // Check if the existing employee frame is already open
        if (!isExistingEmployeeFrameOpen) {
            // Set the flag to indicate that the existing employee frame is now open
            isExistingEmployeeFrameOpen = true;

            FrmExistingEmployee existingEmployeeFrame = new FrmExistingEmployee();
            // Make the frame visible
            existingEmployeeFrame.setVisible(true);

            // Add a window listener to detect when the existing employee frame is closed
            existingEmployeeFrame.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                    // Reset the flag when the existing employee frame is closed
                    isExistingEmployeeFrameOpen = false;
                }
            });
        }
    }//GEN-LAST:event_btnViewEmpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmNewAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new FrmNewAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    public javax.swing.JButton btnSave;
    private javax.swing.JButton btnViewEmp;
    public javax.swing.JComboBox<String> jCBRoleAccess;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEmployeeNum;
    private javax.swing.JLabel lblNote;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRoleAccess;
    private javax.swing.JLabel lblUsername;
    public javax.swing.JTextField txtEmployeeNum;
    public javax.swing.JTextField txtPassword;
    public javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
